export { Dashboard } from './Dashboard'
export { Pessoas } from './Pessoas'
export { Processos } from './Processos'
export { DetalheProcesso } from './DetalheProcesso'
export { Configuracoes } from './Configuracoes'
